# Generated by Django 4.0.6 on 2022-12-27 22:22

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'Resident'), (2, 'KebeleEmploye')], default=1, max_length=10)),
                ('name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('bio', models.TextField(null=True)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Kebele',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kebele_name', models.CharField(help_text='Required', max_length=255, unique=True)),
                ('phone', models.CharField(help_text='Required', max_length=20, null=True)),
                ('email', models.EmailField(help_text='Required', max_length=254)),
                ('address', models.CharField(help_text='Required', max_length=150, verbose_name='City')),
                ('fox_number', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kebele',
                'verbose_name_plural': 'Kebeles',
            },
        ),
        migrations.CreateModel(
            name='Vitalevent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_status', models.CharField(max_length=100, null=True)),
                ('death_date', models.DateTimeField(auto_now_add=True)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vitalevent',
                'verbose_name_plural': 'Vitalevents',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150, null=True)),
                ('sex', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kebele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
            },
        ),
        migrations.CreateModel(
            name='KebeleEmploye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100, null=True)),
                ('lname', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('profile_pic', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=150, null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('qualification', models.BooleanField(default=True)),
                ('bio', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kebele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.kebele')),
            ],
            options={
                'verbose_name': 'KebeleEmploye',
                'verbose_name_plural': 'KebeleEmployes',
            },
        ),
    ]
