# Generated by Django 4.0.6 on 2023-02-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='avatar',
            field=models.ImageField(default='avatar.svg', height_field=80, null=True, upload_to='', width_field=80),
        ),
    ]
