# Generated by Django 4.0.6 on 2022-12-28 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebeleemploye',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='entry.resident'),
        ),
        migrations.AddField(
            model_name='vitalevent',
            name='kebele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kebeles', to='entry.kebele'),
        ),
        migrations.AddField(
            model_name='vitalevent',
            name='marital',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vitalevent',
            name='residents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.resident'),
        ),
        migrations.AlterField(
            model_name='kebele',
            name='address',
            field=models.CharField(help_text='Required', max_length=150, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='kebele',
            name='email',
            field=models.EmailField(help_text='Required', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kebele',
            name='fox_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kebele',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kebeleemploye',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kebeleemploye',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kebeleemploye',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kebeleemploye',
            name='kebele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
        migrations.AlterField(
            model_name='kebeleemploye',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resident',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='kebele',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
        migrations.AlterField(
            model_name='vitalevent',
            name='birth_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalevent',
            name='current_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalevent',
            name='death_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitalevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='entry.resident'),
        ),
    ]
