# Generated by Django 4.0.6 on 2023-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebeleemployee',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kebeleemployee',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kebeleemployee',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
