# Generated by Django 4.0.6 on 2023-01-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='birth_date_id',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='resident',
            old_name='death_date_id',
            new_name='death_date',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='kebele',
        ),
        migrations.AddField(
            model_name='resident',
            name='kebele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.kebele'),
        ),
    ]
