# Generated by Django 4.0.6 on 2023-01-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_rename_birth_date_id_resident_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebeleemploye',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='entry.kebele'),
        ),
    ]
